#!/usr/bin/env python3
"""Book VII -- Freeman Dyson. Replaces the stub."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from figure_chapter import build, TAGCSS

P1 = [
"""Spring 1972, afternoon tea at the Institute for Advanced Study. Hugh Montgomery was a
graduate student visiting from Cambridge; he had been computing the <em>pair correlation</em>
of the zeros of the Riemann zeta function &mdash; how the zeros sit relative to one another
once you have removed the fact that they get denser as you go up. Chowla insisted on
introducing him to Dyson. Dyson asked what he worked on. Montgomery said the pair
correlation of the zeta zeros, and started to write""",

'<div class="box"><div class="box-label">Montgomery&rsquo;s pair correlation, 1972</div>'
'<p class="block-prose" style="text-align:center;font-size:1.2rem">'
'$$R_2(r) = 1 - \\left(\\frac{\\sin \\pi r}{\\pi r}\\right)^2$$</p></div>',

"""and Dyson said, before he had finished, that it was the pair correlation of eigenvalues
of a random Hermitian matrix. He knew because he had derived it, for a completely different
reason, in the early sixties. <span class="tag t-cited">CITED</span>""",

"""Number theory and the energy levels of heavy nuclei had produced the same function, and
nobody had noticed because nobody was in both rooms. <strong>That is the whole content of
this chapter and it is worth more than the anecdote it is usually told as.</strong>""",
]

P2 = [
"""The claim is checkable, and it is checkable from nothing &mdash; no table of zeros, no
library. <code>ch-dyson-verify.py</code> computes the zeros itself with the
Riemann&ndash;Siegel formula, finds 3&thinsp;681 of them below $t = 4200$, agreeing with the
published values of the first ten to a mean error of $2.1\\times10^{-3}$. It unfolds them
by $w_n = \\vartheta(t_n)/\\pi$, so the mean spacing is one, keeps the upper half where the
asymptotics are better, and histograms every pair.""",

'<div class="box"><div class="box-label">1&thinsp;841 unfolded zeros, bin width 0.1</div>'
'<p class="block-prose" style="font-family:ui-monospace,monospace;font-size:.85rem;line-height:1.9">'
'&nbsp;r&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;observed&nbsp;&nbsp;&nbsp;&nbsp;GUE&nbsp;&nbsp;&nbsp;&nbsp;Poisson<br>'
'0.05&nbsp;&nbsp;&nbsp;&nbsp;0.0000&nbsp;&nbsp;&nbsp;0.0082&nbsp;&nbsp;&nbsp;1.0000<br>'
'0.15&nbsp;&nbsp;&nbsp;&nbsp;0.0380&nbsp;&nbsp;&nbsp;0.0719&nbsp;&nbsp;&nbsp;1.0000<br>'
'0.25&nbsp;&nbsp;&nbsp;&nbsp;0.0760&nbsp;&nbsp;&nbsp;0.1894&nbsp;&nbsp;&nbsp;1.0000<br>'
'0.45&nbsp;&nbsp;&nbsp;&nbsp;0.5269&nbsp;&nbsp;&nbsp;0.5119&nbsp;&nbsp;&nbsp;1.0000<br>'
'0.95&nbsp;&nbsp;&nbsp;&nbsp;1.1298&nbsp;&nbsp;&nbsp;0.9973&nbsp;&nbsp;&nbsp;1.0000<br>'
'1.95&nbsp;&nbsp;&nbsp;&nbsp;0.9125&nbsp;&nbsp;&nbsp;0.9993&nbsp;&nbsp;&nbsp;1.0000</p>'
'<p class="block-prose">RMS deviation over $r &lt; 1.5$: <strong>0.078 from GUE, 0.502 from '
'Poisson</strong> &mdash; a factor of 6.4. '
'<span class="tag t-computed">COMPUTED</span></p></div>',

"""The first bin is the one to look at. Uncorrelated points would give $1$. The zeros give
$0$. <strong>They repel each other</strong>, and they repel with exactly the strength that
eigenvalues of a random Hermitian matrix do.""",
]

P3 = [
"""Dyson recognised it because of what he had done a decade earlier, and that is the part
of his work this corpus should be reading.""",

"""In 1962 he asked what kinds of random matrix ensemble are possible at all. Not which
ones are convenient &mdash; which ones <em>exist</em>. A quantum system with a symmetry has
a Hilbert space carrying a representation, and the matrix elements live in whatever field
the commutant allows. Frobenius proved in 1878 that there are exactly three finite-dimensional
associative division algebras over the reals: $\\mathbb{R}$, $\\mathbb{C}$, $\\mathbb{H}$.""",

'<div class="box"><div class="box-label">The threefold way, 1962</div>'
'<p class="block-prose" style="font-family:ui-monospace,monospace;font-size:.88rem;line-height:1.9">'
'&beta; = 1 &nbsp; orthogonal &nbsp; GOE &nbsp; &real; &nbsp;&nbsp; time-reversal, integer spin<br>'
'&beta; = 2 &nbsp; unitary &nbsp;&nbsp;&nbsp;&nbsp; GUE &nbsp; &complexes; &nbsp; no time-reversal<br>'
'&beta; = 4 &nbsp; symplectic &nbsp; GSE &nbsp; &Hopf; &nbsp;&nbsp; time-reversal, half-integer spin</p>'
'<p class="block-prose">Three, and only three, and the number is not a modelling choice. '
'<strong>Frobenius&rsquo; theorem removes every other option.</strong></p></div>',

"""This is <em>ortogênese</em> in the sense the corpus uses it: the classification is
generated by a constraint, in the directions the constraint leaves open. Dyson did not
choose three ensembles. He counted what was left.""",

"""And the zeta zeros landed on $\\beta = 2$ &mdash; the one with no time-reversal symmetry.
Whatever operator has the zeros as its spectrum, if one exists, is not time-reversal
invariant. That is a statement about arithmetic, derived from a theorem about division
algebras, and it is still the strongest structural hint anyone has about what
Hilbert&ndash;P&oacute;lya would have to be. <span class="tag t-open">OPEN</span>""",
]

P4 = [
"""He also wrote the essay this gallery could have been named after. Birds fly high and
see far and unify; frogs live in the mud and see the flowers close up and solve problems.
Dyson said mathematics needs both and that he was a frog, which from the man who unified
Feynman's, Schwinger's and Tomonaga's electrodynamics was either modesty or a very
precise self-assessment.""",

"""The corpus should notice one more thing. In 1952 Dyson proved that the perturbation
series of quantum electrodynamics &mdash; the series whose agreement with experiment is the
most accurate in physics &mdash; <strong>diverges</strong>. Not converges slowly: has zero
radius of convergence. The argument is a page long and turns on what happens if the
coupling is negative: the vacuum becomes unstable, so the function cannot be analytic at
the origin.""",

'''<div class="box"><div class="box-label">Why that belongs here</div>
<p class="block-prose">A divergent series that predicts to twelve digits is the cleanest
existing example of the thing this corpus keeps insisting on: <strong>a result can be
correct, useful, experimentally confirmed, and resting on something that is not
established.</strong> Physics kept using the series, correctly, and wrote down what it had
not proved. That is the epistemic standard, demonstrated by someone who had every
incentive not to.</p></div>''',
]

build(
 slug="dyson",
 name="Freeman Dyson",
 hero_sub="At tea in 1972 a graduate student started writing a formula about prime numbers and "
          "Dyson finished it, because he had derived the same function for the energy levels of "
          "heavy nuclei. Two rooms, one function, nobody in both.",
 description="Freeman Dyson: the Montgomery pair correlation recognised as GUE, verified here "
             "from 3681 Riemann zeros computed by Riemann-Siegel, and the threefold way as a "
             "classification forced by Frobenius' theorem.",
 parts=[
   ("Part I &middot; Tea at the Institute", "The formula he finished", P1),
   ("Part II &middot; The Check", "Computed from nothing", P2),
   ("Part III &middot; Why He Knew", "Three, because there are only three", P3),
   ("Part IV &middot; Birds, Frogs, and a Divergent Series", "What he was willing to say", P4),
 ],
 place_rows=[
   ("C", "unfolding &mdash; the density removed, only the correlation left",
        "compression: strip what is not structure"),
   ("K", "Frobenius: $\\mathbb{R}$, $\\mathbb{C}$, $\\mathbb{H}$ and nothing else",
        "the constraint that removes options"),
   ("F", "$\\beta \\in \\{1,2,4\\}$ &mdash; three ensembles, not a continuum",
        "the fold &mdash; threshold, not scale <span class=\"tag t-shown\">SHOWN</span>"),
   ("U", "the zeta zeros landing on $\\beta = 2$",
        "the branch arithmetic chose <span class=\"tag t-computed\">COMPUTED</span>"),
 ],
 refs=[
  "F. J. Dyson, &ldquo;The threefold way. Algebraic structure of symmetry groups and ensembles in quantum mechanics&rdquo;, <em>J. Math. Phys.</em> 3, 1962, 1199&ndash;1215.",
  "F. J. Dyson, &ldquo;Divergence of perturbation theory in quantum electrodynamics&rdquo;, <em>Phys. Rev.</em> 85, 1952, 631&ndash;632.",
  "H. L. Montgomery, &ldquo;The pair correlation of zeros of the zeta function&rdquo;, <em>Proc. Symp. Pure Math.</em> 24, 1973, 181&ndash;193.",
  "A. M. Odlyzko, &ldquo;On the distribution of spacings between zeros of the zeta function&rdquo;, <em>Math. Comp.</em> 48, 1987 &mdash; the large-scale numerical confirmation.",
  "F. J. Dyson, &ldquo;Birds and Frogs&rdquo;, <em>Notices of the AMS</em> 56, 2009, 212&ndash;223.",
  "F. G. Frobenius, &ldquo;&Uuml;ber lineare Substitutionen und bilineare Formen&rdquo;, <em>Crelle</em> 84, 1878 &mdash; the three real division algebras.",
 ],
 prev=("ch-bak.html", "Per Bak"),
 nxt=("ch-erdos.html", "Paul Erd&#337;s"),
 verify="book7/ch-dyson-verify.py",
 extra_css=TAGCSS,
)
