#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pablo Nogueira Grossi / G6 LLC
"""
ch-atiyah-verify.py -- the numerical half of WP-82's two remaining index candidates.

WP-82 showed lambda_perp = e^{-4pi} is not an index because it MOVES with the base
point. It named three candidates for a class that would not move. ch-conley closed
the third (Conley). This closes the other two -- the topology by hand, cited, and
the numbers here.

Blocks
  [1] Gamma winds exactly once per period: the K^1(S^1) generator evaluates to 1.
  [2] lambda(z) = -2(1 - e^{-z}) -> -2, so the multiplier -> e^{-4pi} at the z -> oo end.
  [3] The drift WP-82 measured: the multiplier is strictly monotone in z0 and
      takes a continuum of non-integer values. An index does none of that.
  [4] Reparametrisation rdot -> k*rdot moves the multiplier over many orders while
      winding is untouched -- ch-conley's argument, re-run on the K^1 generator.
  [5] Control.

Standard library only. Exit 0 iff every block holds.
"""
import math, sys

ok = True
def check(c, msg):
    global ok
    print(("  ok    " if c else "  FAIL  ") + msg)
    if not c: ok = False

TSTAR = 2 * math.pi
lam    = lambda z: -2.0 * (1.0 - math.exp(-z))          # transverse eigenvalue
mult   = lambda z: math.exp(lam(z) * TSTAR)             # Floquet multiplier

print("[1] The winding of Gamma -- the K^1(S^1) generator")
# On Gamma: rdot = 0, thetadot = 1, zdot = 1. Over one period T* = 2pi,
# theta advances by exactly 2pi: winding number 1.
w = (1.0 * TSTAR) / (2 * math.pi)
check(abs(w - 1.0) < 1e-15, "theta advances 2pi over T* = 2pi -> winding number = %d (an integer)" % round(w))

print("\n[2] The z -> oo end")
check(abs(lam(40) + 2.0) < 1e-15, "lambda(z) -> -2")
check(abs(mult(40) - math.exp(-4 * math.pi)) < 1e-12,
      "multiplier -> e^{-4pi} = %.12e" % math.exp(-4 * math.pi))
check(abs(math.exp(-4 * math.pi) - round(math.exp(-4 * math.pi))) > 1e-9,
      "and e^{-4pi} is not an integer, so it is not the value of an index")

print("\n[3] The drift WP-82 measured")
zs = [0.5, 1.0, 2.0, 4.0, 8.0]
vals = [mult(z) for z in zs]
for z, v in zip(zs, vals):
    print("      z0 = %-5g  multiplier = %.9e" % (z, v))
check(all(vals[i] > vals[i + 1] for i in range(len(vals) - 1)),
      "strictly monotone in the base point -- an index is deformation invariant")
check(len({round(v, 12) for v in vals}) == len(vals), "a continuum of distinct values, none an integer")

print("\n[4] Reparametrisation: rdot -> k*rdot")
for k in (1e-3, 1.0, 1e3, 1e6):
    m = math.exp(k * lam(8.0) * TSTAR)
    print("      k = %-8g  multiplier = %.6e   winding = 1" % (k, m))
check(math.exp(1e-3 * lam(8.0) * TSTAR) > 0.9 and math.exp(1e3 * lam(8.0) * TSTAR) < 1e-300,
      "the multiplier moves over >300 orders; the winding number does not move at all")

print("\n[5] Control")
check(abs(lam(0.0)) < 1e-15, "lambda(0) = 0 -- Gamma is not hyperbolic at z = 0")

print()
print("  THE TOPOLOGY, cited rather than computed here:")
print("    M = {(r,theta,z) : r > 0} = (R^2 minus 0) x R,  which deformation retracts to S^1.")
print("    K~^0(S^1) = 0   -- every complex vector bundle over S^1 is trivial")
print("    K^1(S^1) = Z    -- generated by the winding/determinant class")
print("    A = {z <= c} retracts to M, so the pair is trivial and K*(M, A) = 0.")
print()
print("  all blocks hold." if ok else "  FAILURES ABOVE.")
sys.exit(0 if ok else 1)
