-- NASAGaps.lean (repository root) — SUPERSEDED 2026-09-11
--
-- This file was a stale copy of Orthogenesis/Architecture/NASAGaps.lean. Its
-- own first line said so: it carried that path as its header while sitting at
-- the repository root. It was tracked but outside every `lake build` target,
-- so nothing ever type-checked it, and it could not have type-checked in any
-- case — it imported `Orthogenesis.Architecture.Colony`, a module that does
-- not exist in this repository (the file is `Orthogenesis.Geometry.Colony`).
--
-- It is neutralised rather than left in place because it asserted, as a live
-- theorem, a claim withdrawn from the authoritative file:
--
--     theorem FN_P_101L_schumann_proximity :
--         |(g6_int : ℝ) - 33.516| / 33.516 < 2 / 100 := g6_within_2pct_of_f4
--
-- `g6_int`, `g6_within_2pct_of_f4` and the whole of G6Crystal §4 were withdrawn
-- on 2026-09-11 (see Orthogenesis/Architecture/G6Crystal.lean §4 for the four
-- reasons). A reviewer reading the repository would have found the withdrawn
-- claim still stated here in proof form. An uncompiled file is not a harmless
-- file: it is a claim nothing is checking.
--
-- The authoritative gap ledger is Orthogenesis/Architecture/NASAGaps.lean.
-- The prior contents of this file remain in git history.
--
-- Deliberately empty of declarations: no imports, nothing to elaborate.
