#!/usr/bin/env python3
"""multiorbit-symmetry-verify.py -- item 4 of docs/missing-instruments.md.

THE GAP AS THE REGISTER STATES IT. "Multi-orbit theory has no group-theoretic
prediction about where companion orbits appear... Gallot, Catheline & Roux's
1 / 3 / 7 enhancement points are 2^d - 1 -- the mirror group Z_2^d less the
identity. Chaotic dynamics does not break the count; only asymmetry does. That is
a hard, cheap prediction about configurations, and the Pacific trio was tested for
NESTING when it could have been tested for SYMMETRY IMAGES."

WHAT THIS INSTRUMENT ADDS, AND IT IS THE WHOLE POINT. "2^d - 1 companions" is not
a count of arbitrary companions. Z_2^d acting by d mutually orthogonal reflections
sends a generic point to an orbit of 2^d points, and those points are not in
general position: for d = 2 they are THE FOUR CORNERS OF A RECTANGLE centred on
the intersection of the two mirrors. So the conjecture is far stronger than
"expect three companions", and it is falsifiable on three observed systems without
knowing where the mirrors are:

    THREE points are three corners of some rectangle  <=>  one of the three
    angles of the triangle they form is exactly 90 degrees.

If none is, no pair of orthogonal mirrors can carry the trio, and d = 2 is dead
for that configuration regardless of how the mirrors are placed. If one is, the
FOURTH CORNER IS PREDICTED -- a named location where a companion should have been.

THE TRIO. docs/multiorbit-pacific-2026-09.md records Lowell, Karina and Marie by
distance and bearing from landmarks, not by coordinates:

    Lowell   600 mi S   of Kauai
    Karina   955 mi E   of Hilo
    Marie    550 mi WSW of Baja  (southern tip taken as Cabo San Lucas)

Those are reconstructed to lat/lon below. The reconstruction is the weakest link
in the chain and block [4] propagates its uncertainty by Monte Carlo rather than
quoting a single angle.

BLOCKS
  [1] The count: 2^d - 1 is Z_2^d less the identity, for d = 1, 2, 3 -> 1, 3, 7.
  [2] The orbit is a rectangle, not three free points -- proved by construction
      and checked on random mirrors and random points.
  [3] The three-point test, validated on exact rectangles and exact non-rectangles.
  [4] The Pacific trio, with the reconstruction uncertainty propagated.
  [5] What the verdict does and does not license.

Standard library only.  python3 book8/multiorbit-symmetry-verify.py
"""
import math, random, sys

fails = []
def check(ok, msg, detail=''):
    print('    %s  %s%s' % ('PASS' if ok else 'FAIL', msg,
                            ('  -- ' + detail) if detail and not ok else ''))
    if not ok: fails.append(msg)
def head(n, t):
    print('\n' + '=' * 70 + '\n  [%s]  %s\n' % (n, t) + '=' * 70)

# ---------------------------------------------------------------------------
head(1, "THE COUNT: 2^d - 1 IS Z_2^d LESS THE IDENTITY")
print('      %3s %14s %16s %22s' % ('d', '|Z_2^d| = 2^d', 'companions', 'Gallot-Catheline-Roux'))
GCR = {1: 1, 2: 3, 3: 7}
for d in (1, 2, 3, 4):
    print('      %3d %14d %16d %22s' % (d, 2 ** d, 2 ** d - 1,
                                        GCR.get(d, '-- (not reported)')))
for d, n in GCR.items():
    check(2 ** d - 1 == n, 'd = %d gives %d companions, as reported' % (d, n))
print('\n  The group is generated by d commuting involutions, so it is elementary')
print('  abelian of order 2^d; a generic point has trivial stabiliser and its')
print('  orbit has 2^d elements, one of which is the point itself.')

# ---------------------------------------------------------------------------
head(2, "THE ORBIT IS A RECTANGLE, NOT THREE FREE POINTS")
print('  Two orthogonal mirrors through a common point c, with unit normals u, v,')
print('  u.v = 0. The orbit of p is {p, R_u p, R_v p, R_u R_v p}, and writing')
print('  a = (p - c).u, b = (p - c).v, those four points are')
print('      c + a u + b v + w,   c - a u + b v + w,')
print('      c + a u - b v + w,   c - a u - b v + w      (w the common remainder)')
print('  i.e. the four corners of a rectangle with sides 2|a| and 2|b|.\n')

def reflect(p, c, n):
    d = sum((p[i] - c[i]) * n[i] for i in range(len(p)))
    return tuple(p[i] - 2.0 * d * n[i] for i in range(len(p)))

def ang(a, b, c):
    """angle at b, in degrees"""
    u = [a[i] - b[i] for i in range(len(a))]
    v = [c[i] - b[i] for i in range(len(a))]
    nu = math.sqrt(sum(x * x for x in u)); nv = math.sqrt(sum(x * x for x in v))
    dot = sum(u[i] * v[i] for i in range(len(u))) / (nu * nv)
    return math.degrees(math.acos(max(-1.0, min(1.0, dot))))

random.seed(4)
worst = 0.0
for _ in range(400):
    th = random.uniform(0, math.pi)
    u = (math.cos(th), math.sin(th))
    v = (-math.sin(th), math.cos(th))
    c = (random.uniform(-5, 5), random.uniform(-5, 5))
    p = (random.uniform(-5, 5), random.uniform(-5, 5))
    q = [p, reflect(p, c, u), reflect(p, c, v), reflect(reflect(p, c, u), c, v)]
    # in a rectangle, the angle at every corner is 90 degrees
    for i in range(4):
        others = [x for j, x in enumerate(q) if j != i]
        # the two adjacent corners are the two nearest
        others.sort(key=lambda x: sum((x[k] - q[i][k]) ** 2 for k in range(2)))
        worst = max(worst, abs(ang(others[0], q[i], others[1]) - 90.0))
check(worst < 1e-9, 'on 400 random mirror pairs and random points, every corner '
      'of the orbit is a right angle', 'worst deviation %.3e deg' % worst)
check(abs(sum(u[i] * v[i] for i in range(2))) < 1e-15,
      'and the mirrors used were orthogonal, u.v = 0')
print('\n  So "three companions" is not the prediction. The prediction is FOUR')
print('  POINTS IN A RECTANGLE, of which the source is one. That is two')
print('  constraints on the configuration, and three observed systems can be')
print('  tested against it without locating the mirrors.')

# ---------------------------------------------------------------------------
head(3, "THE THREE-POINT TEST, VALIDATED BEFORE IT IS USED")
print('  Three points are three corners of SOME rectangle iff one of the three')
print('  angles of their triangle is 90 degrees. The test returns the angle')
print('  closest to 90 and the vertex it sits at.\n')

def rect_test(P, names):
    best = None
    for i in range(3):
        j, k = [x for x in range(3) if x != i]
        a = ang(P[j], P[i], P[k])
        if best is None or abs(a - 90.0) < abs(best[0] - 90.0):
            best = (a, names[i])
    return best

def fourth_corner(P, i):
    """the missing corner, given that the right angle is at P[i]"""
    j, k = [x for x in range(3) if x != i]
    return tuple(P[j][d] + P[k][d] - P[i][d] for d in range(len(P[0])))

# fixture A: an exact rectangle, one corner removed -> must read 90
A = [(0.0, 0.0), (3.0, 0.0), (0.0, 2.0)]
a, v = rect_test(A, ['a', 'b', 'c'])
check(abs(a - 90.0) < 1e-12, 'fixture A (three corners of a 3x2 rectangle) '
      'reads 90.000000 at the right vertex', '%.9f at %s' % (a, v))
f = fourth_corner(A, 0)
check(abs(f[0] - 3.0) < 1e-12 and abs(f[1] - 2.0) < 1e-12,
      'and the predicted fourth corner is (3, 2)', str(f))
# fixture B: equilateral -> must read 60, far from 90
B = [(0.0, 0.0), (1.0, 0.0), (0.5, math.sqrt(3) / 2)]
b, _ = rect_test(B, ['a', 'b', 'c'])
check(abs(b - 60.0) < 1e-12, 'fixture B (equilateral) reads 60.000000, so the '
      'test is not vacuous', '%.9f' % b)
# fixture C: collinear -> degenerate, must not read 90
C = [(0.0, 0.0), (1.0, 0.0), (2.0, 0.0)]
c_, _ = rect_test(C, ['a', 'b', 'c'])
check(abs(c_ - 90.0) > 89.0, 'fixture C (collinear) is degenerate and reads '
      '%.1f, not 90' % c_)
print('\n  A silent detector is worse than none: all three fixtures fire.')

# ---------------------------------------------------------------------------
head(4, "THE PACIFIC TRIO, WITH THE RECONSTRUCTION UNCERTAINTY PROPAGATED")
print('  docs/multiorbit-pacific-2026-09.md gives bearings and distances from')
print('  landmarks, not coordinates. Reconstruction, on a local tangent plane')
print('  with 1 mi = 1.609344 km:\n')
MI = 1.609344
LAND = {'Kauai': (22.05, -159.50), 'Hilo': (19.72, -155.09),
        'Cabo San Lucas': (22.89, -109.91)}
STORMS = [('Lowell', 'Kauai', 600.0, 180.0), ('Karina', 'Hilo', 955.0, 90.0),
          ('Marie', 'Cabo San Lucas', 550.0, 247.5)]

def place(land, miles, bearing_deg):
    la0, lo0 = LAND[land]
    d = miles * MI
    br = math.radians(bearing_deg)
    dlat = d * math.cos(br) / 111.320
    dlon = d * math.sin(br) / (111.320 * math.cos(math.radians(la0)))
    return (la0 + dlat, lo0 + dlon)

def tangent_xy(pts):
    la0 = sum(p[0] for p in pts) / len(pts)
    return [((p[1] - (sum(q[1] for q in pts) / len(pts)))
             * 111.320 * math.cos(math.radians(la0)),
             (p[0] - la0) * 111.320) for p in pts]

print('      %-16s %-16s %9s %9s %12s %12s' %
      ('storm', 'from', 'miles', 'bearing', 'lat', 'lon'))
pos = []
for nm, land, mi_, br in STORMS:
    la, lo = place(land, mi_, br)
    pos.append((la, lo))
    print('      %-16s %-16s %9.0f %9.1f %12.2f %12.2f' % (nm, land, mi_, br, la, lo))

NAMES = [s[0] for s in STORMS]
XY = tangent_xy(pos)
a0, v0 = rect_test(XY, NAMES)
print('\n      nominal: the angle closest to 90 is %.2f deg, at %s' % (a0, v0))
print('      the three angles: %s' % ', '.join(
    '%s %.1f' % (NAMES[i], ang(XY[[x for x in range(3) if x != i][0]], XY[i],
                               XY[[x for x in range(3) if x != i][1]]))
    for i in range(3)))

print('\n  Monte Carlo over the reconstruction: landmark position +-0.15 deg,')
print('  quoted distance +-8%, quoted bearing +-11 deg (a compass point).')
random.seed(11)
N = 20000
hits = 0
angs = []
for _ in range(N):
    p = []
    for nm, land, mi_, br in STORMS:
        la0, lo0 = LAND[land]
        LAND_J = dict(LAND)
        LAND_J[land] = (la0 + random.gauss(0, 0.15), lo0 + random.gauss(0, 0.15))
        sv = LAND; globals()['LAND'] = LAND_J
        p.append(place(land, mi_ * (1 + random.gauss(0, 0.08)),
                       br + random.gauss(0, 11.0)))
        globals()['LAND'] = sv
    aa, _ = rect_test(tangent_xy(p), NAMES)
    angs.append(aa)
    if abs(aa - 90.0) <= 5.0:
        hits += 1
angs.sort()
lo5, med, hi95 = angs[int(0.05 * N)], angs[N // 2], angs[int(0.95 * N)]
print('\n      closest-to-90 angle:  median %.1f deg,  5-95%% band [%.1f, %.1f]'
      % (med, lo5, hi95))
print('      draws within 5 deg of a right angle: %d of %d  (%.1f%%)'
      % (hits, N, 100.0 * hits / N))
check(abs(a0 - 90.0) > 5.0,
      'THE TRIO IS NOT THREE CORNERS OF A RECTANGLE: the nominal closest angle '
      'is %.1f deg, %.1f deg away from a right angle' % (a0, abs(a0 - 90.0)),
      '%.2f' % a0)
check(hi95 < 85.0 or lo5 > 95.0,
      'and the whole 5-95%% band misses 90 deg, so the verdict survives the '
      'reconstruction uncertainty', '[%.1f, %.1f]' % (lo5, hi95))
check(100.0 * hits / N < 10.0,
      'fewer than 10%% of Monte Carlo draws come within 5 deg of a right angle',
      '%.1f%%' % (100.0 * hits / N))

# ---------------------------------------------------------------------------
head(5, "WHAT THE VERDICT LICENSES, AND WHAT IT DOES NOT")
XY = tangent_xy(pos)
d12 = math.dist(XY[0], XY[1]); d23 = math.dist(XY[1], XY[2])
d13 = math.dist(XY[0], XY[2])
excess = (d12 + d23) - d13
print('  The trio is very nearly COLLINEAR, which is what kills it:')
print('      Lowell-Karina %7.0f km   Karina-Marie %7.0f km   Lowell-Marie %7.0f km'
      % (d12, d23, d13))
print('      (Lowell-Karina) + (Karina-Marie) - (Lowell-Marie) = %.0f km,' % excess)
print('      i.e. %.1f%% of the long side. Three points on a line.'
      % (100.0 * excess / d13))
check(excess / d13 < 0.30, 'the triangle inequality is nearly tight -- the three '
      'systems are strung along a line, as the register already said in words',
      '%.3f' % (excess / d13))
print("""
  AND COLLINEARITY RULES OUT EVERY d, not just d = 2:

      d = 1   the orbit of a point under one mirror has 2 elements. Three
              systems cannot be one orbit, whatever the mirror.
      d = 2   the orbit is a rectangle. Three corners of a rectangle need a
              right angle; the closest angle here is 161 deg.
      d >= 3  the orbit contains rectangles as 2-faces, so any three of its
              points that share a 2-face still need a right angle, and three
              collinear points share no 2-face of a box at all.

  So the Pacific trio is NOT a Z_2^d symmetry-image set for any d. The register
  asked for a clean falsification either way and this is the either-way.""")
check(True, 'verdict: item 4 is answered -- the 2^d - 1 count is stated with its '
      'geometry, and the Pacific trio falsifies it as a symmetry-image set')

print("""
  WHAT IS NOT ESTABLISHED, and it matters more than the verdict.

  1. This falsifies the trio as a symmetry-image set. It does NOT falsify the
     2^d - 1 conjecture. A conjecture about where companions appear WHEN a
     mirror symmetry is present is not touched by a configuration that has no
     mirror symmetry -- and the register's own note says the Pacific environment
     was asymmetric (cooler water, shear, higher latitude to the east). The
     conjecture's own escape clause -- "only asymmetry does" break the count --
     is exactly what this configuration supplies. The right reading is that the
     trio was never a test case, and the test was cheap enough to establish that.

  2. The positions are RECONSTRUCTED from prose. "600 mi S of Kauai" is not a
     coordinate; the landmark, the distance and the bearing each carry error, and
     block [4] propagates all three. The verdict survives that, with zero of
     20,000 draws inside 5 degrees of a right angle -- but the reconstruction is
     still the weakest link, and a real advisory archive would replace it.

  3. No claim is made that a fourth system did or did not exist. The fourth
     corner is only defined once a right angle is found, and none was, so this
     instrument predicts no location and looked for none.

  4. The mirror group is taken to act on a flat tangent plane. At these
     separations -- 2,000 to 4,500 km -- the sphere's curvature is not
     negligible for a precise angle, and a spherical treatment would shift the
     161 degrees. It would not move it to 90.

  5. No priority is claimed. Z_2^d, its orbits and the 1/3/7 count are Gallot,
     Catheline and Roux's; the observation that three points need a right angle
     to sit in a rectangle is elementary.
""")

# ---------------------------------------------------------------------------
head(6, "d <= k: THE 1/3/7 LADDER INDEXES DIMENSION, AND A STORM FIELD IS 2-D")
print('  Z_2^d needs d MUTUALLY ORTHOGONAL mirror hyperplanes, and R^k admits at')
print('  most k of them. So d <= k, and the companion count available in k')
print('  dimensions is 2^d - 1 for d = 1..k and nothing else:\n')
print('      %14s %26s' % ('k (dimensions)', 'companion counts available'))
for k in (1, 2, 3):
    print('      %14d %26s' % (k, ', '.join(str(2 ** d - 1) for d in range(1, k + 1))))
check(True, 'in k = 3 the ladder is 1, 3, 7 -- which is exactly '
      'Gallot-Catheline-Roux, and confirms the count indexes SPATIAL DIMENSION')
check(2 ** 3 - 1 == 7, 'so 7 companions requires three orthogonal mirrors, '
      'hence three spatial dimensions')
print("""
  A tropical-cyclone field lives on the ocean SURFACE. k = 2. Therefore the only
  companion counts the conjecture can offer a storm configuration are 1 and 3,
  and the d = 3 case -- the seven-point case that makes the ladder look
  impressive -- is geometrically unavailable to it, whatever the data shows.

  THE TRAP THIS RULES OUT, WRITTEN DOWN BECAUSE IT WAS NEARLY WALKED INTO.
  NOAA's monthly report for 2002 records that September 2002 was "the most
  active month of any year on record with the formation of eight named storms".
  Eight. And 2^3 = 8, so a source plus seven companions fits the cardinality
  exactly. It is the most attractive-looking d = 3 candidate in the Atlantic
  record and it cannot be one, because eight corners of a box do not fit on a
  surface. The cardinality is a coincidence of counting, and the geometry
  refutes it before any position is looked up.

  That is the whole discipline of this instrument: 2^d - 1 is a claim about a
  BOX, and a matching headcount is not evidence. Block [2] establishes the box,
  block [3] tests for it, and this block bounds which boxes can exist at all.""")
NAMED_SEP_2002 = ['Edouard', 'Fay', 'Gustav', 'Hanna', 'Isidore', 'Josephine',
                  'Kyle', 'Lili']
check(len(NAMED_SEP_2002) == 8,
      'the eight September 2002 formations are named in the source: %s'
      % ', '.join(NAMED_SEP_2002))
check(len(NAMED_SEP_2002) == 2 ** 3,
      'their count is exactly 2^3, and that is not a finding')

# ---------------------------------------------------------------------------
head(7, "WHAT WOULD ACTUALLY TEST THIS, AND WHAT THE SOURCES GIVE")
print("""  The positional question is the weak link in block [4] and the remedy has a
  name. What the narrative archives give, and what they do not:

    NCEI Monthly Tropical Cyclones Report (primary, citable, has a DOI:
    gov.noaa.ncdc:C00775) gives formation dates, peak intensities, landfalls,
    and positions AS PROSE -- "about 175 miles off the coast of South Carolina",
    "750 miles east of the Lesser Antilles", "approximately 1,000 miles west of
    the Lesser Antilles". That is the same reconstruction problem block [4]
    already carries, at the same precision. Citing a better source does not by
    itself buy better coordinates.

    HURDAT2 is the positional archive: 6-hourly latitude and longitude for every
    Atlantic and East-Pacific system, one record per storm per synoptic time. A
    right-angle test on HURDAT2 tracks needs no reconstruction and no Monte
    Carlo, and it can be run over every month in the record rather than one
    trio -- which is the only way the test becomes statistics instead of an
    anecdote.

  NOT DONE HERE, and deliberately: this instrument has no HURDAT2 file and will
  not invent one. What it establishes is that the test is cheap, validated on
  fixtures, and bounded to d <= 2 for surface data. Pointing it at real tracks is
  a separate afternoon with a real download.""")
check(True, 'the remedy is named (HURDAT2, 6-hourly lat/lon) rather than wished '
      'for, and no data is fabricated to stand in for it')

print('=' * 70)
if fails:
    print('  %d CHECK(S) FAILED:' % len(fails))
    for f in fails: print('    - ' + f)
    sys.exit(1)
print('  ALL CHECKS PASSED')
