#!/usr/bin/env python3
"""qm5-verify.py — Chapter QM5: braiding as computation; Fibonacci vs Ising.

Standard library only. The two-dimensional braid representations of Fibonacci
and Ising anyons (four anyons, total charge fixed) are built from their F and R
data; the braid relation is checked; and the groups they generate are explored
by breadth-first closure, modulo overall phase.

  [1] Fusion rule tau x tau = 1 + tau gives the Bratteli diagram: the number of
      fusion paths of n tau's to total charge 1 is Fib(n-1), to tau is Fib(n);
      the quantum dimension d = lim Fib(n+1)/Fib(n) is the golden ratio.
  [2] F = [[1/phi, 1/sqrt(phi)], [1/sqrt(phi), -1/phi]]: unitary, F^2 = I,
      and phi^2 = phi + 1.  R = diag(exp(-4 pi i/5), exp(3 pi i/5)).
  [3] Braid relation: sigma_1 = R, sigma_2 = F R F satisfy
      sigma_1 sigma_2 sigma_1 = sigma_2 sigma_1 sigma_2   (the hexagon, in
      this basis, is what makes this hold), and both are unitary.
  [4] Ising (sigma anyons, 4 of them, charge 1): sigma_1 = diag(e^{-i pi/8},
      e^{3 i pi/8}), sigma_2 = H sigma_1 H: braid relation holds; BFS closure
      modulo phase is FINITE, of size exactly 24 (the one-qubit Clifford
      group mod phase) — braiding cannot be universal.
  [5] Fibonacci closure modulo phase does NOT close: the number of distinct
      elements keeps growing with word length up to the search limit. This is
      evidence for density, not a proof of it (the proof is Freedman-Larsen-
      Wang); the script says so.
  [6] Controls (each must FAIL): sigma_2 = R F R^-1 F-less variant breaks the
      braid relation; a wrong R phase breaks it; the Ising closure test would
      report 'infinite' if the group were not Clifford (it is not run on a
      non-Clifford phase gate: with e^{-i pi/8} replaced by e^{-i pi/7} the
      closure exceeds the limit).
  [7] Sourcing against Nayak-Simon-Stern-Freedman-Das Sarma (arXiv:0707.1889)
      in ~/Downloads (SKIP if absent).
  [8] Sourcing against Freedman-Larsen-Wang (arXiv quant-ph/0001108v2) in
      ~/Downloads (SKIP if absent): the density theorem is about the Jones
      representation of B6 at q = e^{2 pi i/5}, and the words Fibonacci and Ising
      do not occur in that paper (control: both occur in the Nayak review).

    python3 quantum-maths/qm5-verify.py
"""
import cmath, math, os, re, subprocess, sys

FAIL = []
def check(ok, msg):
    print(("    PASS  " if ok else "    FAIL  ") + msg)
    if not ok: FAIL.append(msg)
def head(n, t):
    print('\n' + '=' * 68 + '\n  [%s]  %s\n' % (n, t) + '=' * 68)

TOL = 1e-12
def mm(A, B): return [[sum(A[i][k] * B[k][j] for k in range(2)) for j in range(2)] for i in range(2)]
def dag(A): return [[A[j][i].conjugate() for j in range(2)] for i in range(2)]
def dist(A, B): return max(abs(A[i][j] - B[i][j]) for i in range(2) for j in range(2))
I2 = [[1 + 0j, 0j], [0j, 1 + 0j]]

head(1, 'Bratteli diagram: paths = Fibonacci numbers; d = golden ratio')
fibs = [0, 1]
for _ in range(30): fibs.append(fibs[-1] + fibs[-2])
def paths(n):
    """vector (ways to total charge 1, ways to total charge tau) after fusing n tau's (n >= 1)"""
    one, tau = 0, 1                                       # a single tau has charge tau
    for _ in range(n - 1):
        one, tau = tau, one + tau                         # tau x 1 = tau; tau x tau = 1 + tau
    return one, tau
ok = all(paths(n) == (fibs[n - 1], fibs[n]) for n in range(1, 25))
check(ok, 'paths of n tau-anyons: to charge 1 is Fib(n-1), to charge tau is Fib(n), n = 1..24')
phi = (1 + math.sqrt(5)) / 2
check(abs(fibs[30] / fibs[29] - phi) < 1e-10 and abs(phi * phi - phi - 1) < TOL, 'Fib(n+1)/Fib(n) -> phi = %.12f and phi^2 = phi + 1' % phi)

head(2, 'F and R for the Fibonacci anyon')
a, b = 1 / phi, 1 / math.sqrt(phi)
F = [[a + 0j, b + 0j], [b + 0j, -a + 0j]]
R = [[cmath.exp(-4j * math.pi / 5), 0j], [0j, cmath.exp(3j * math.pi / 5)]]
check(dist(mm(dag(F), F), I2) < TOL, 'F is unitary')
check(dist(mm(F, F), I2) < TOL, 'F^2 = I (so F = F^-1)')
check(abs(a * a + b * b - 1) < TOL, 'the rows of F are unit vectors: 1/phi^2 + 1/phi = 1')
check(dist(mm(dag(R), R), I2) < TOL, 'R is unitary')

head(3, 'the braid relation for Fibonacci')
s1 = R; s2 = mm(mm(F, R), F)
lhs, rhs = mm(mm(s1, s2), s1), mm(mm(s2, s1), s2)
check(dist(lhs, rhs) < 1e-11, 'sigma_1 sigma_2 sigma_1 = sigma_2 sigma_1 sigma_2 (gap %.1e)' % dist(lhs, rhs))
check(dist(mm(dag(s2), s2), I2) < TOL, 'sigma_2 = F R F is unitary')

def canon(M):
    """canonical form modulo overall phase, rounded"""
    for i in range(2):
        for j in range(2):
            if abs(M[i][j]) > 1e-6:
                ph = M[i][j] / abs(M[i][j]); N = [[M[r][c] / ph for c in range(2)] for r in range(2)]
                return tuple((round(N[r][c].real, 6) + 0.0, round(N[r][c].imag, 6) + 0.0) for r in range(2) for c in range(2))
def closure(gens, limit):
    """BFS over the group generated by gens (and their inverses), modulo phase"""
    gens = gens + [dag(g) for g in gens]
    seen = {canon(I2): I2}; frontier = [I2]; sizes = []
    while frontier and len(seen) <= limit:
        nxt = []
        for M in frontier:
            for g in gens:
                P = mm(g, M); key = canon(P)
                if key not in seen:
                    seen[key] = P; nxt.append(P)
        frontier = nxt; sizes.append(len(seen))
    return len(seen), (not frontier), sizes

head(4, 'Ising: finite closure of exactly 24 elements')
H = [[1 / math.sqrt(2) + 0j, 1 / math.sqrt(2) + 0j], [1 / math.sqrt(2) + 0j, -1 / math.sqrt(2) + 0j]]
i1 = [[cmath.exp(-1j * math.pi / 8), 0j], [0j, cmath.exp(3j * math.pi / 8)]]
i2 = mm(mm(H, i1), H)
check(dist(mm(mm(i1, i2), i1), mm(mm(i2, i1), i2)) < 1e-11, 'Ising: sigma_1 sigma_2 sigma_1 = sigma_2 sigma_1 sigma_2')
n_ising, closed, _ = closure([i1, i2], 5000)
check(closed and n_ising == 24, 'the group generated, modulo phase, closes at exactly %d elements (one-qubit Clifford group is 24)' % n_ising)

head(5, 'Fibonacci: no closure within the search limit')
n_fib, closed_f, sizes = closure([s1, s2], 20000)
print('      distinct elements (mod phase) after each BFS layer:', sizes[:14], '...')
check((not closed_f) and n_fib > 20000, 'Fibonacci closure exceeds %d elements without closing (finite groups here would have stopped at 24 or 60 or 120)' % 20000)
print('      NOTE: this is evidence for density, not a proof of it. Density in SU(2)')
print('      (hence universality of braiding for Fibonacci) is the theorem of')
print('      Freedman, Larsen and Wang; this script does not reproduce it.')

head(6, 'controls')
bad1 = mm(mm(R, F), R)                                       # a wrong sigma_2
check(dist(mm(mm(s1, bad1), s1), mm(mm(bad1, s1), bad1)) > 0.01, 'sigma_2 = R F R breaks the braid relation')
Rw = [[cmath.exp(-3j * math.pi / 5), 0j], [0j, cmath.exp(3j * math.pi / 5)]]
w2 = mm(mm(F, Rw), F)
check(dist(mm(mm(Rw, w2), Rw), mm(mm(w2, Rw), w2)) > 0.01, 'a wrong R phase (e^{-3 pi i/5}) breaks the braid relation')
j1 = [[cmath.exp(-1j * math.pi / 7), 0j], [0j, cmath.exp(3j * math.pi / 7)]]
j2 = mm(mm(H, j1), H)
n_bad, closed_b, _ = closure([j1, j2], 3000)
check((not closed_b) and n_bad > 3000, 'with e^{-i pi/7} in place of e^{-i pi/8} the closure is NOT finite: the closure test can say infinite')

head(7, 'the sourcing, against Nayak et al. in ~/Downloads')
_D = next((q for q in (os.path.expanduser('~/Downloads/'), os.path.expanduser('~/mnt/Downloads/')) if os.path.isdir(q)), None)
txt = None
if _D:
    for fn in os.listdir(_D):
        if fn.lower().startswith('non-abeliananyonsandtopologicalquantumcomputation'):
            try:
                o = subprocess.run(['pdftotext', '-layout', os.path.join(_D, fn), '-'], capture_output=True, text=True, timeout=180)
                if o.returncode == 0 and o.stdout:
                    txt = re.sub(r'\s+', ' ', o.stdout.replace('ﬁ', 'fi').replace('ﬂ', 'fl'))
            except Exception:
                txt = None
if txt is None:
    print('    SKIP  the review (or pdftotext) is not available; none of the sourcing below is checked')
else:
    for label, needle in [
        ('Fibonacci fusion rule tau x tau = 1 + tau', 'τ ×τ =1+τ'),
        ('dimension of the Hilbert space is Fib(n-1)', 'is given by the Fibonacci number Fib(n − 1)'),
        ('Fibonacci model is universal', 'capable of universal quantum computation'),
        ('Ising needs a non-topological gate', 'non-topological operations'),
        ('pentagon equation named', 'pentagon equation'),
        ('hexagon equation named', 'hexagon equation'),
        ('Freedman-Larsen-Wang 2002a in the reference list', 'A modular'),
        ('R for fusion to 1: e^(-4 pi i/5)', 'e−4πi/5'),
        ('R for fusion to tau, Eq. (133) and the 3-anyon matrix: -e^(-2 pi i/5)', '−e−2πi/5'),
    ]:
        check(needle in txt, 'Nayak et al. record: ' + label)
    # The review's prose line after Eq. (133) prints R^tau_{tau tau} = -e^{+2 pi i/5} (exponent sign
    # differs from Eq. (133) in the PDF text layer itself). Test which one the braid relation accepts:
    alt = [[cmath.exp(-4j * math.pi / 5), 0j], [0j, -cmath.exp(2j * math.pi / 5)]]
    alt2 = mm(mm(F, alt), F)
    gap_alt = dist(mm(mm(alt, alt2), alt), mm(mm(alt2, alt), alt2))
    Reqn = [[cmath.exp(-4j * math.pi / 5), 0j], [0j, -cmath.exp(-2j * math.pi / 5)]]
    Reqn2 = mm(mm(F, Reqn), F)
    gap_eqn = dist(mm(mm(Reqn, Reqn2), Reqn), mm(mm(Reqn2, Reqn), Reqn2))
    check(gap_eqn < 1e-11 and gap_alt > 0.1,
          'braid relation accepts Eq. (133), R_tau = -e^(-2 pi i/5) = e^(3 pi i/5) (gap %.1e), and REJECTS the review\'s prose line -e^(+2 pi i/5) (gap %.3f): the prose line has a sign typo' % (gap_eqn, gap_alt))

head(8, 'the sourcing, against Freedman-Larsen-Wang (arXiv quant-ph/0001108v2) in ~/Downloads')
def _pdf_norm(prefix):
    if not _D: return None
    for fn in os.listdir(_D):
        if fn.lower().startswith(prefix):
            try:
                o = subprocess.run(['pdftotext', '-layout', os.path.join(_D, fn), '-'], capture_output=True, text=True, timeout=180)
                if o.returncode == 0 and o.stdout:
                    return re.sub(r'\s+', ' ', o.stdout.replace('\ufb01', 'fi').replace('\ufb02', 'fl'))
            except Exception:
                return None
    return None
flw = _pdf_norm('a modular functor which is universal')
if flw is None:
    print('    SKIP  the Freedman-Larsen-Wang PDF (or pdftotext) is not available; none of the sourcing below is checked')
else:
    for label, needle in [
        ('arXiv identifier quant-ph/0001108', 'quant-ph/0001108'),
        ('Theorem 4.1 is stated', 'Theorem 4.1. Let'),
        ('closure of the image contains SU(5) x SU(8)', 'contains SU(5) × SU(8)'),
        ('the representation is at the 5-th root of unity', '5-th root of unity'),
        ('the model is Chern-Simons at the fifth root of unity', 'fifth root of unity'),
        ('Theorem 2.1 (braid approximation of two-qubit gates)', 'Theorem 2.1.'),
        ('BQP simulation (Theorem 2.3)', 'BQP'),
    ]:
        check(needle in flw, 'Freedman-Larsen-Wang record: ' + label)
    low = flw.lower()
    check(not re.search(r'\bfibonacci\b', low), 'the word Fibonacci does not occur in the Freedman-Larsen-Wang paper')
    check(not re.search(r'\bising\b', low), 'the word Ising does not occur in the Freedman-Larsen-Wang paper')
    if txt is None:
        print('    SKIP  control for the two absence checks (the Nayak review is not available): they could not be shown able to fail')
    else:
        tl = txt.lower()
        check(bool(re.search(r'\bfibonacci\b', tl)) and bool(re.search(r'\bising\b', tl)), 'control: the same search finds Fibonacci and Ising in the Nayak review, so the absence checks can fail')

print()
if FAIL:
    print('FAILED: %d check(s)' % len(FAIL)); sys.exit(1)
print('all checks passed'); sys.exit(0)
