/-
  book28/CliffordSmall.lean — two anticommuting square roots of −1, and the rotation of Atiyah's trick.
  Principia Orthogona, Book XXVIII ch 6. Pablo Nogueira Grossi, G6 LLC, 2026.

  Bott periodicity is organised by Clifford algebras: algebras generated by anticommuting square
  roots of −1. With two of them one gets Hamilton's quaternions. This file checks, in Mathlib's
  ℍ[ℝ], that i² = j² = −1 and ij = −ji, so Cl₀,₂ ≅ ℍ has the defining relations. It also checks
  the 2×2 block rotation [[0, −1], [1, 0]] used in "Atiyah's trick" (Zois, Lecture 4): it squares
  to −1 and has determinant 1 (a quarter-turn, joined to the identity by rotations).

  WHAT IS NOT HERE: no vector bundle, no K-group, no periodicity theorem.
-/
import Mathlib.Algebra.Quaternion
import Mathlib.Data.Real.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Data.Matrix.Mul

open scoped Quaternion

namespace CliffordSmall

/-- Hamilton's units. -/
def qi : ℍ[ℝ] := ⟨0, 1, 0, 0⟩
def qj : ℍ[ℝ] := ⟨0, 0, 1, 0⟩

theorem qi_sq : qi * qi = -1 := by ext <;> simp [qi]
theorem qj_sq : qj * qj = -1 := by ext <;> simp [qj]
/-- The two generators anticommute: the Clifford relation. -/
theorem qi_qj_anticomm : qi * qj = -(qj * qi) := by ext <;> simp [qi, qj]

/-- The rotation in Atiyah's trick. -/
def J : Matrix (Fin 2) (Fin 2) ℤ := !![0, -1; 1, 0]

theorem J_sq : J * J = -1 := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [J, Matrix.mul_apply, Fin.sum_univ_two]
theorem J_det : J.det = 1 := by simp [J, Matrix.det_fin_two]

end CliffordSmall

#print axioms CliffordSmall.qi_sq
#print axioms CliffordSmall.qj_sq
#print axioms CliffordSmall.qi_qj_anticomm
#print axioms CliffordSmall.J_sq
#print axioms CliffordSmall.J_det
