#!/usr/bin/env python3
"""ch00-verify.py — Chapter 0 (Definitions and Notation), Book X · Custody, Transmission, and the Continent. Generated by tools/chapter_zero.py (R6)."""
import os, subprocess, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.exit(subprocess.call([sys.executable, os.path.join(root, "tools", "chapter_zero_verify.py"), "--book", "10"]))
