#!/usr/bin/env python3
"""The series rule must be on both covers, and must survive a regeneration.

Usage:  python3 tools/series_rule_check.py          (from the repository root)

The rule -- "people are passed over a lot, and then the mathematics gets
another status" -- is the series' standing statement. It sits on two pages:

  series-hub.html    the series cover, hand-maintained
  master-index.html  the full-repo index, GENERATED by tools/build_indexes.py

The second is the reason this script exists. `master-index.html` is written
from scratch on every run of the generator, so a statement typed into it is
destroyed by the next build -- silently, with the file still looking finished.
The rule therefore lives in the generator as `DIDACTIC` and is emitted, and
this script checks three things rather than one:

  1. the rule is on `series-hub.html`;
  2. the rule is on `master-index.html`;
  3. the rule is in `tools/build_indexes.py`, so (2) is not an accident of the
     last build that a future one will undo.

Point 3 is the whole point. A statement that is present in the output and
absent from the generator is not present; it is pending deletion.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

RULE = "People are passed over a lot, and then the mathematics gets another status."
SUPPORT = [
    "A result you cannot attribute is a result you cannot yet argue with.",
    "Anonymity is what lets a claim get promoted without being checked",
]

TARGETS = [
    ("series-hub.html",           "the series cover"),
    ("master-index.html",         "the generated full-repo index"),
    ("tools/build_indexes.py",    "the generator that writes it"),
]


def main() -> int:
    fail = []
    for rel, what in TARGETS:
        p = ROOT / rel
        if not p.exists():
            fail.append("%s (%s) does not exist" % (rel, what))
            continue
        t = p.read_text(encoding="utf-8", errors="replace")
        ok = RULE in t
        print("  %-24s %-32s %s" % (rel, what, "ok" if ok else "MISSING"))
        if not ok:
            if rel == "master-index.html":
                fail.append("%s does not carry the rule -- rerun tools/build_indexes.py" % rel)
            elif rel.startswith("tools/"):
                fail.append("the rule is not in the generator: whatever is in "
                            "master-index.html today will be erased by the next build")
            else:
                fail.append("%s (%s) does not carry the rule" % (rel, what))

    hub = (ROOT / "series-hub.html")
    if hub.exists():
        t = hub.read_text(encoding="utf-8", errors="replace")
        for s in SUPPORT:
            if s not in t:
                fail.append("series-hub.html has the rule but not its method: %r" % s[:48])

    for f in fail:
        print("::error::" + f)
    if fail:
        return 1
    print("the series rule is on both covers and in the generator that rewrites one of them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
